name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install
        working-directory: client 

      - name: Build Next.js app
        run: npm run build
        working-directory: client
      - run: npm run export
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build_dir
          path: ./out

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync static files to S3
        run: aws s3 sync client/build/ s3://abad2024-react/
